# Generated by Django 3.0.3 on 2020-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_topic', models.CharField(max_length=64, verbose_name='뉴스 주제')),
                ('news_topic_detail', models.CharField(max_length=64, verbose_name='뉴스 소주제')),
                ('news_headline', models.CharField(max_length=256, verbose_name='뉴스 제목')),
                ('news_url', models.CharField(max_length=256, verbose_name='뉴스 URL')),
                ('news_company', models.CharField(max_length=64, verbose_name='뉴스 회사')),
                ('news_time', models.CharField(max_length=64, verbose_name='뉴스 시간')),
                ('news_contents', models.TextField(verbose_name='뉴스 본문')),
                ('news_comments', models.CharField(max_length=64, verbose_name='뉴스 댓글수')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '다음 뉴스',
                'verbose_name_plural': '다음 뉴스',
                'db_table': 'daum_news_scraping',
            },
        ),
    ]
