# Generated by Django 3.0.3 on 2020-04-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsscrapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyPurposeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_purpose', models.CharField(max_length=64, verbose_name='수집 목적')),
            ],
            options={
                'verbose_name': '다음 뉴스 목적(temp)',
                'verbose_name_plural': '다음 뉴스 목적(temp)',
                'db_table': 'daum_news_purpose',
            },
        ),
    ]
